config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  resources :users 
  resources :comments
  resources :groups

  root 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :memberships
  has_many :users, :through => :memberships

  def comments
    Comment.scoped(:joins => {:user => :memberships}, :conditions => { :memberships => { :group_id => id } })
  end
  
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :group

=begin
  def self.update_membership_attributes
    @group = Membership.joins(:user).where(:user_id => @user.id)
      @groups = params[:user][:group_ids]
      @groups.each do |group|
        @group.group_id => group
        user_id => @user.id)
      end
  end	
=end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :memberships	
  has_many :comments
  has_many :groups, :through => :memberships
  #attr_accessor :group_ids
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    # this will find out all the comment where "admin" column column value in the users table is true.
    @comments = Comment.joins(:user).where("users.admin"=> true).order("comments.created_at asc")   
  end
  
  def show
    @comment = Comment.find(params[:id])
  end
  
  def new
    @comment = Comment.new
  end
  
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      flash[:notice] = "Successfully created comment."
      redirect_to @comment
    else
      render :action => 'new'
    end
  end
  
  def edit
    @comment = Comment.find(params[:id])
  end
  
  def update
    @comment = Comment.find(params[:id])
    if @comment.update_attributes(comment_params)
      flash[:notice] = "Successfully updated comment."
      redirect_to @comment
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:notice] = "Successfully destroyed comment."
    redirect_to comments_url
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :user_id)
  end 
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
  end
  
  def show
    @group = Group.find(params[:id])
  end
  
  def new
    @group = Group.new
  end
  
  def create
    @group = Group.new(group_params)
    if @group.save
      flash[:notice] = "Successfully created group."
      redirect_to @group
    else
      render :action => 'new'
    end
  end
  
  def edit
    @group = Group.find(params[:id])
  end
  
  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(group_params)
      flash[:notice] = "Successfully updated group."
      redirect_to @group
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    flash[:notice] = "Successfully destroyed group."
    redirect_to groups_url
  end

  private
  
  def group_params
    params.require(:group).permit(:name)
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end  
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.joins(:memberships).new(user_params)
    if @user.save
      @groups = params[:user][:group_ids]
      @groups.each do |group|
        Membership.create(:group_id => group, :user_id => @user.id)
      end
      flash[:notice] = "Successfully created user."
      redirect_to @user
    else
      render :action => 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update_attributes(user_params)
    redirect_to @user
    #@group = Membership.joins(:user).where(:user_id => @user.id)
    #@groups = params[:user][:group_ids]
    #@groups.each do |group|
      #@user.update_attributes(params[:user][:group])
    #end
    #@user = User.find(params[:id])
    #Membership.update_user_membership
  end  
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "Successfully destroyed user."
    redirect_to users_url
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :admin, {:group_ids => []})
  end

end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
  <%= simple_format comment.content %>
  <p class="actions">
    <%= link_to "edit", edit_comment_path(comment) %> |
    <%= link_to "destroy", comment, :method => :delete, :confirm => "Are you sure?" %>
  </p>
</div>

app/views/comments/_form.html.erb
<%= form_for @comment do |f| %>
  <%#= f.error_messages %>
  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.label :user_id %><br />
    <%= f.collection_select :user_id, User.all, :id, :name %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/comments/edit.html.erb
<%# title "Edit Comment" %>

<%= render :partial => 'form' %>

<p>
  <%= link_to "Show", @comment %> |
  <%= link_to "View All", comments_path %>
</p>

app/views/comments/index.html.erb
<%# title "Comments" %>

<%= render @comments %>

<p><%= link_to "New Comment", new_comment_path %></p>

app/views/comments/new.html.erb
<h1>Add Comments</h1>
<%= form_for @comment do |f| %>
  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.label :user_id %><br />
    <%= f.collection_select :user_id, User.all, :id, :name %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

<p><%= link_to "Back to List", comments_path %></p>

app/views/comments/show.html.erb
<%# title "Comment" %>

<p>
  <strong>Content:</strong>
  <%=h @comment.content %>
</p>
<p>
  <strong>User:</strong>
  <%=h @comment.user_id %>
</p>

<p>
  <%= link_to "Edit", edit_comment_path(@comment) %> |
  <%= link_to "Destroy", @comment, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", comments_path %>
</p>

app/views/groups/_form.html.erb
<%= form_for @group do |f| %>
  <%#= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/groups/edit.html.erb
<%# title "Edit Group" %>
<%= render :partial => 'form' %>
<p>
  <%= link_to "Show", @group %> |
  <%= link_to "View All", groups_path %>
</p>

app/views/groups/index.html.erb
<%# title "Groups" %>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% for group in @groups %>
    <tr>
      <td><%=h group.name %></td>
      <td><%= link_to "Show", group %></td>
      <td><%= link_to "Edit", edit_group_path(group) %></td>
      <td><%= link_to "Destroy", group, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Group", new_group_path %></p>

app/views/groups/new.html.erb
<%# title "New Group" %>

<%= render :partial => 'form' %>

<p><%= link_to "Back to List", groups_path %></p>

app/views/groups/show.html.erb
<% #title @group.name %>
<%= @group.name %>
<p>
  <%= link_to "Edit", edit_group_path(@group) %> |
  <%= link_to "Destroy", @group, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "See All Groups", groups_path %>
</p>

<h2>Users</h2>
<ul>
<%# for user in @group.users %>
  <li><%#=h user.name %></li>
<%# end %>
</ul>

<h2>Comments</h2>

<%#= render @group.comments %>

app/views/home/index.html.erb
<h1>welcome</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IncludeJoin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= link_to "create_user", new_user_path %>
  <%= link_to "create_comment", new_comment_path %>
  <%= link_to "create_group", new_group_path %>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%#= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.check_box :admin %> <%= f.label :admin %>
  </p>
  <p>
  <% for group in Group.all %>
    <%= check_box_tag "user[group_ids][]", group.id, @user.groups.include?(group) %>
    <%=h group.name %><br />
  <% end %>
  </p>
  <%#= hidden_field_tag "user[group_ids][]"%>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/users/edit.html.erb
<%# title "Edit User" %>

<%= render :partial => 'form' %>
<p>
  <%= link_to "Show", @user %> |
  <%= link_to "View All", users_path %>
</p>

app/views/users/index.html.erb
<%# title "Users" %>

<% for user in @users %>
<p class="user">
  <strong><%= link_to h(user.name), user %></strong>
  <%= "(admin)" if user.admin? %><br />
  
  <%= pluralize user.comments.count, "comment" %><br />
  
  <%= link_to "Edit", edit_user_path(user) %> |
  <%= link_to "Destroy", user, :confirm => 'Are you sure?', :method => :delete %>
</p>
<% end %>

<p><%= link_to "New User", new_user_path %></p>

app/views/users/new.html.erb
<%#= title "New User" %>

<%= render :partial => 'form' %>

<p><%= link_to "Back to List", users_path %></p>

app/views/users/show.html.erb
<%# title "User" %>

<p>
  <strong>Name:</strong>
  <%=h @user.name %>
</p>
<p>
  <strong>Admin:</strong>
  <%=h @user.admin %>
</p>
<strong>Groups</strong>
  <% @user.groups.each do |group|%>
    <%= group.name %>
  <% end %>
<p>
  <%= link_to "Edit", edit_user_path(@user) %> |
  <%= link_to "Destroy", @user, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", users_path %>
</p>